CREATE TABLE IF NOT EXISTS TB_CATEGORIES (
id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
name VARCHAR(20) NOT NULL,
UNIQUE(name),
PRIMARY KEY(id)
);

INSERT INTO TB_CATEGORIES (name) VALUES ("jam");
INSERT INTO TB_CATEGORIES (name) VALUES ("router");
INSERT INTO TB_CATEGORIES (name) VALUES ("book");