CREATE TABLE IF NOT EXISTS TB_ROLES (
id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
ROLE VARCHAR(10) DEFAULT 'ROLE_USER',
user_id BIGINT UNSIGNED NOT NULL,
CONSTRAINT fk_user FOREIGN KEY(user_id) REFERENCES TB_USERS (id)
ON DELETE CASCADE
ON UPDATE RESTRICT,
UNIQUE (user_id,ROLE),
PRIMARY KEY(id)
);

INSERT INTO TB_ROLES (ROLE,user_id) VALUES ('ROLE_USER',1);
INSERT INTO TB_ROLES (ROLE,user_id) VALUES ('ROLE_ADMIN',1);
INSERT INTO TB_ROLES (ROLE,user_id) VALUES ('ROLE_USER',2);