CREATE TABLE IF NOT EXISTS TB_PRODUCTS (
id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
title VARCHAR(50) NOT NULL,
price MEDIUMINT UNSIGNED DEFAULT 0,
unit VARCHAR(10) NOT NULL,
createdTime DATETIME DEFAULT CURRENT_TIMESTAMP,
lastModified DATETIME DEFAULT CURRENT_TIMESTAMP,
enabled TINYINT UNSIGNED DEFAULT 0,
category_id BIGINT UNSIGNED NOT NULL,
CONSTRAINT fk_category_id
		FOREIGN KEY (category_id) REFERENCES TB_CATEGORIES (id)
		ON DELETE CASCADE
		ON UPDATE RESTRICT,
UNIQUE(title),
PRIMARY KEY(id)
);

INSERT INTO TB_PRODUCTS(title,price,unit,enabled,category_id) VALUES("蘋果手工果醬",175,"罐",1,1);
INSERT INTO TB_PRODUCTS(title,price,unit,enabled,category_id) VALUES("藍莓手工果醬",165,"罐",1,1);
INSERT INTO TB_PRODUCTS(title,price,unit,enabled,category_id) VALUES("MT7620A路由器",620,"個",1,2);
INSERT INTO TB_PRODUCTS(title,price,unit,enabled,category_id) VALUES("RT-N14U路由器",610,"個",1,2);